apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  labels:
    app: cockroachdb
spec:
  ports:
  - port: 26257
    name: grpc
  - port: 8080
    name: http
  selector:
    app: cockroachdb
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: roach
spec:
  serviceName: "cockroachdb"
  replicas: 3
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
        app.kubernetes.io/component: cockroachdb 
    spec:
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:v23.1.10
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 26257
          name: grpc
        - containerPort: 8080
          name: http
          
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        command:
        - "/bin/bash"
        - "-ecx"
        - "exec /cockroach/cockroach start --insecure --join=roach-0.cockroachdb:26257,roach-1.cockroachdb:26257,roach-2.cockroachdb:26257 --listen-addr=0.0.0.0 --cache=256Mi --max-sql-memory=256Mi --store=path=/cockroach/cockroach-data"
        
        volumeMounts:
        - name: datadir
          mountPath: /cockroach/cockroach-data
          subPath: ""
          subPathExpr: $(POD_NAME)
          
      volumes:
      - name: datadir
        hostPath:
          path: /mnt/data
          type: Directory